-- Database & schema (run once if not exists)
CREATE DATABASE IF NOT EXISTS TRANSIT_GFTS;
CREATE SCHEMA IF NOT EXISTS TRANSIT_GFTS.BRONZE;

-- Raw Bronze table (append-only)
CREATE OR REPLACE TABLE TRANSIT_GFTS.BRONZE.RAW_MTA_DATA (
    RAW_JSON VARIANT,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
